name: Build PS5 JAR Loader

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
      # run: mvn clean package -P xploitOnDisc
        run: mvn clean package 


      - name: Install genisoimage
        run: sudo apt-get update && sudo apt-get install -y genisoimage


      - name: Create ISO from AVCHD Contents
        run: |
          cd assembly/target/assembly-*/AVCHD
          genisoimage -udf -o ../ps5-jar-loader.iso .  
        # genisoimage -udf -o ../ps5-jar-loader-all.iso .  


      - name: Upload Assembly Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ps5-jar-loader
          path: assembly/target/assembly-*/ps5-jar-loader.iso

        # name: ps5-jar-loader-all
        # path: assembly/target/assembly-*/ps5-jar-loader-all.iso

      - name: Upload Payload JARs
        uses: actions/upload-artifact@v4
        with:
          name: ps5-jar-files
          path: xploit/*/target/*.jar
